version: '3'

services:
  webserver:
    build: ./bin/php/7.3
    ports:
      - ${WEBSERVER_HOST_PORT}:80
    volumes:
      - ${WEBSERVER_WEB_DIR}:/var/www/html
      - ${WEBSERVER_LOG_DIR}:/var/log/apache2
  database:
    image: mysql:8.0
    ports:
      - ${DATABASE_HOST_PORT}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ${DATABASE_DATA_DIR}:/var/lib/mysql